# Generated by Django 3.2.13 on 2022-04-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_auto_20220430_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminhod',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='2.jpg', null=True, upload_to=''),
        ),
    ]
