# Generated by Django 3.2.13 on 2022-05-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0014_auto_20220501_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='avatar.svg', upload_to='profile_pic'),
        ),
    ]
