# Generated by Django 3.2.13 on 2022-05-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0015_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='profile_picture',
            field=models.ImageField(default='avatar.svg', upload_to='student_profile_pic'),
        ),
    ]
