# Generated by Django 3.2.13 on 2022-05-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0016_subjects_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='students',
            name='profile_picture',
            field=models.ImageField(default='avatar.svg', upload_to='student_profile_pic'),
        ),
    ]
