# Generated by Django 3.2.13 on 2022-05-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0017_auto_20220502_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='profile_picture',
            field=models.ImageField(blank=True, default='avatar.svg', null=True, upload_to='student_profile_pic'),
        ),
    ]
