# Generated by Django 3.2.13 on 2022-05-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0020_staffs_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminhod',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='adminhod',
            name='gender',
            field=models.CharField(default='Male', max_length=50),
        ),
    ]
