# Generated by Django 3.2.13 on 2022-05-05 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0021_auto_20220505_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationstaffs',
            old_name='stafff_id',
            new_name='staff_id',
        ),
        migrations.RemoveField(
            model_name='adminhod',
            name='address',
        ),
        migrations.RemoveField(
            model_name='adminhod',
            name='gender',
        ),
        migrations.AlterField(
            model_name='subjects',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.staffs'),
        ),
    ]
